// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
// biome-ignore-all lint: autogenerated file

import en from "./en/index.js";
import { initFormatters } from "./formatters.js";
import fr from "./fr/index.js";
import type { Locales, Translations } from "./i18n-types.js";
import { loadedFormatters, loadedLocales, locales } from "./i18n-util.js";

const localeTranslations = {
	en,
	fr
};

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return;

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations;
	loadFormatters(locale);
};

export const loadAllLocales = (): void => locales.forEach(loadLocale);

export const loadFormatters = (locale: Locales): void => void (loadedFormatters[locale] = initFormatters(locale));
