# Generated by Django 4.2.3 on 2023-07-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelid', models.TextField(unique=True)),
                ('messageid', models.TextField(unique=True)),
                ('category', models.JSONField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('creator', models.TextField(blank=True)),
                ('createdat', models.IntegerField(blank=True)),
                ('claimedby', models.TextField(blank=True, null=True)),
                ('claimedat', models.IntegerField(blank=True, null=True)),
                ('closedby', models.TextField(blank=True, null=True)),
                ('closedat', models.IntegerField(blank=True)),
                ('closereason', models.TextField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets_Temp_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickets')),
            ],
            options={
                'db_table': 'tickets_temp_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tickets_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_codeName', models.CharField(blank=True, max_length=255, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('creator_username', models.CharField(blank=True, max_length=255, null=True)),
                ('claimedby_username', models.CharField(blank=True, max_length=255, null=True)),
                ('closedby_username', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('claimedat', models.DateTimeField(blank=True, null=True)),
                ('closedat', models.DateTimeField(blank=True, null=True)),
                ('ticket_info_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickets')),
            ],
            options={
                'db_table': 'tickets_info',
                'managed': True,
            },
        ),
    ]
